### ISSUE TITLE
Update guzzlehttp/guzzle to 7v

### ISSUE THREAD

**Issue by jadamec** [xnekv03/nameday-api#4]
Cannot install via composer when using the 7v of the `guzzlehttp/guzzle`

  Problem 1
    - Root composer.json requires xnekv03/nameday-api ^2.0 -> satisfiable by xnekv03/nameday-api[v2.0.0].
    - xnekv03/nameday-api v2.0.0 requires guzzlehttp/guzzle ^6.5 -> found guzzlehttp/guzzle[6.5.0, ..., 6.5.x-dev] but it conflicts with your root
 composer.json require (^7.0.1).

**Comment by xnekv03** [comment]
Thanks @jadamec for spotting this fixed in v2.0.1
