### ISSUE TITLE
API license

### ISSUE THREAD

**Issue by ccoVeille** [xnekv03/nameday-api#85]
Hi @xnekv03 

The web site seems to mention you are maintaining the lib to call the API and the API

I didn't find the code or repository of the API you are using. So I'm writing you there.

I'm interested in knowing the license associated to the data your API retrieve.

Your API is interesting for me because I would like to retrieve the list of all firstnames to add them into a dictionary

While I'm OK with your API not to be open-source (unless I missed something), I'm curious from where you got the content and if there is a license associated to them.

Thanks

**Comment by ccoVeille** [comment]
Here is the project I was talking about

https://github.com/streetsidesoftware/cspell-dicts/discussions/3327#discussioncomment-9845617

**Comment by xnekv03** [comment]
Hello and thanks for interest in my project.
Data comes from my private database and api is under MIT license.
Can I reach out to you 1:1?
My telegram account is xnekv03

Thanks

**Comment by ccoVeille** [comment]
I don't have telegram. But signal, slack, discord. It's enough I hope

**Comment by xnekv03** [comment]
My signal username is xnekv.03

**Comment by ccoVeille** [comment]
For records and for anyone curious, we contacted each other and started talking about what we could do

**Comment by xnekv03** [comment]
@ccoVeille it´s there

**Comment by ccoVeille** [comment]
Amazing @xnekv03 thanks!

cc @lego3s

**Comment by ccoVeille** [comment]
Fixed by fdd39bd67e6a344148400e7780b156dd8ac385cb
